# Generated by Django 4.1.7 on 2023-02-21 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('yazar', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('yayim_tarixi', models.DateTimeField(auto_now_add=True)),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('yenilenme_tarixi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_sahibi', models.CharField(max_length=255)),
                ('yorum', models.TextField(blank=True, null=True)),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('yenilenme_tarixi', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('kitab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kitablar.kitab')),
            ],
        ),
    ]
