# Generated by Django 4.1.7 on 2023-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitablar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitab',
            name='yayim_tarixi',
            field=models.DateTimeField(),
        ),
    ]
